first/urls.py
from django.conf.urls import url
from . import views

app_name= 'first'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^index/$', views.index, name='index'),
    url(r'^hospital_user/$', views.hospital_user, name='hospital_user'),
    url(r'^view/$', views.view, name='view'),
    #url(r'^record/$', views.record, name='record'),
    url(r'^index/record/(?P<user_id>(\d+))/(?P<document_id>(\d+))/$', views.record, name='record'),
    url(r'^search/', views.search, name='search'),
    url(r'^(?P<user_id>[0-9]+)/$', views.detail, name='detail'),
    #url(r'^(?P<document_id>[0-9]+)/[A-Z]+$', views.ind_record, name='ind_record'),
    url(r'^index/(?P<user_id>[0-9]+)/record/(?P<document_id>[0-9]+)/$', views.record, name='record'),
    url(r'^(?P<user_id>[0-9]+)/record/$', views.record, name='record'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    #url(r'^document/add/$', views.DocumentCreate.as_view(), name='document-add'),
    url(r'^create/$', views.CreateDocument.as_view(), name='create'),
    url(r'^delete/$', views.DocumentDelete.as_view(), name='document-delete'),
    url(r'^(?P<user_id>[0-9]+)/delete_document/(?P<document_id>[0-9]+)/$', views.delete_document, name='delete_document'),
    #url(r'^create/$', views.create, name='create'),


    url(r'^python/$', views.python, name='python'),
    #url(r'^(?P<user_id>[0-9]+)/python/(?P<document_id>[0-9]+)/$', views.python,name='python'),

    #url(r'^index/python/(?P<user_id>[0-9]+)/$', views.python, name='python'),
    url(r'^index/(?P<user_id>[0-9]+)/python/$', views.python, name='python'),
    #url(r'^(?P<user_id>[0-9]+)/(?P<document_id>[0-9]+)/python/$', views.python, name='python'),
    #url(r'^(?P<user_id>[0-9]+)/python/(?P<document_id>[0-9]+)/$', views.python, name='python'),
    #url(r'^python/(?P<user_id>(\d+))/(?P<document_id>(\d+))/$', views.python, name='python'),
    #url(r'^index/python/(?P<user_id>[0-9]+)/(?P<document_id>[0-9]+)/$', views.python, name='python'),

    #url(r'^first/login/$', views.LoginFormView.as_view, name='login'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^document/(?P<user_id>[0-9]+)/delete/$', views.DocumentDelete.as_view(), name='document-delete'),
]

rajagiri/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/', include("first.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

# Create your models here.
class User(models.Model):
    Hospital_id = models.CharField(max_length=100)
    Firstname = models.CharField(max_length=200)
    Lastname = models.CharField(max_length=200)
    Age = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(1)])
    Address = models.CharField(max_length=500)
    Phone_Number = models.CharField(max_length=12)

    def __str__(self):
        return self.Hospital_id + "-" + self.Firstname

class Document(models.Model):
    Hospital_id = models.ForeignKey(User, on_delete=models.CASCADE)
    Document_type = models.CharField(max_length=20)
    Document_image = models.FileField()

    def get_absolute_url(self):
        return reverse('first:detail', kwargs={'pk':self.pk})

first/forms.py
from django.contrib.auth.models import User
from . models import Document
from django import forms

class UserForm(forms.ModelForm):
    CHOICES = [('select1', 'Admin'),
               ('select2', 'Doctor'),
               ('select3', 'Staff')]
    Type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password','first_name','last_name','Type']

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.Type = self.cleaned_data["Type"]
        if commit:
            user.save()
        return user


class AuthenticationForm(forms.ModelForm):
    password = forms.CharField(min_length=6, max_length=25, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password']

class AddDocumentForm(forms.ModelForm):
    Document_image = forms.FileField()
    class Meta:
        model = Document
        fields = ['Hospital_id', 'Document_type', 'Document_image']

first/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from . models import User, Document
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
#login
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, AddDocumentForm
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

# To run python scripts
from subprocess import run, PIPE
import sys

# Create your views here.
def home(request):
    #return HttpResponse("<h1>Rajagiri Project</h1>")
    return render(request, 'first/home.html')

def index(request):
    #documents = Document.objects.filter()
    all_users = User.objects.all()
    #return render(request, 'first/index.html', {'documents': documents})
    return render(request, 'first/index.html', {'all_users': all_users})
    #patient = get_object_or_404(User, pk=user_id)
    #return render(request, 'first/detail.html', {'patient': patient})


def view(request):
    if request.user.is_staff:
        all_users = User.objects.all()
        return render(request, 'first/view.html', {'all_users': all_users})
    else:
        return render(request,'first/home.html')

def record(request, user_id, document_id):
    patient = get_object_or_404(User, pk=user_id)
    document = Document.objects.get(pk=document_id)
    context = {
        'patient': patient,
        'document': document, }

    return render(request, 'first/record.html', context)

def detail(request, user_id):
    #return HttpResponse("<h2>Details for User ID: "+ str(user_id)+" </h2>")
    #user = User.objects.get(pk=user_id)
    patient = get_object_or_404(User, pk=user_id)

    return render(request, 'first/detail.html', {'patient': patient})

def ind_record(request, user_id, document_id):


    return render(request, 'first/record.html', context)



#login
class LoginFormView(View):
    form_class = AuthenticationForm
    template_name = 'first/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        #form = self.form_class(request.POST)
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                #return render(request, 'first/view.html', {'name': request.user.username})
                #request.user.username
                #return render(request, 'first:view')
                return redirect('first:home')
                #return HttpResponse("Signed in ")
                #return redirect('first:home', {'name': request.user.username})
                #return render(request, 'first/view.html', {'users': request.user.username})
        else:
            #return render(request, 'first/view.html', {'error': 'Email or Password is incorrect'})
            return HttpResponse("Invalid Credentials <br/> Please go back and Login again")



class UserFormView(View):
    form_class = UserForm
    template_name = 'first/registration_form.html'

    #signup , shows the page
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #sends data to database
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # to get normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            #signin if the credentials are correct

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    # request.user.username prints username
                    return redirect('first:home')

        return render(request, self.template_name, {'form': form})

def logout_user(request):
    logout(request)
    return redirect('first:login')
    form = UserForm(request.POST or None)
    context = {
        "form": form
    }
    return render(request, 'first/login.html', context)

class DocumentCreate(CreateView):
    model = Document
    fields = ['Hospital_id','Document_type','Document_image']
    template_name = 'first/document_form.html'

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # to get normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()


def delete_document(request, user_id, document_id):
    patient = get_object_or_404(User, pk=user_id)
    document = Document.objects.get(pk=document_id)
    document.delete()
   # return render(request, 'first/index.html')
    #return HttpResponseRedirect("first/index")
    return redirect('first:index')


class DocumentDelete(DeleteView):
    model = Document
    success_url = reverse_lazy('first:home')

class CreateDocument(View):
    template_name = 'first/document_form.html'

    def get(self, request):
        form = AddDocumentForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if request.method == "POST":
            form = AddDocumentForm(request.POST,request.FILES)

            if form.is_valid():
                user = form.save(commit=False)
                # to get normalized data
                Hospital_id = form.cleaned_data['Hospital_id']
                Document_type = form.cleaned_data['Document_type']



                user.save()
                return redirect('first:index')

                #signin if the credentials are correct





        return render(request, self.template_name, {'form': form})


def create(request):
    if request.method == "POST":
        form = AddDocumentForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # to get normalized data
            Hospital_id = form.cleaned_data['Hospital_id']
            Document_type = form.cleaned_data['Document_type']

            user.save()


        else:
            form = AddDocumentForm()

        return render(request, 'first/document_form.html',{"form":form})


def search(request):

    search_term = ''

    if 'search' in request.GET:
        search_term = request.GET['search']
        patients = User.objects.all().filter(Hospital_id__icontains=search_term)

    return render(request, 'first/search.html', {'patients': patients, 'search_term': search_term})

def hospital_user(request):
    return render(request, 'first/hospital_user.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            #return render(request, 'first/change_password.html')
            return render(request, 'first/hospital_user.html')
            return redirect('first:hospital_user.html')
        else:
            messages.error(request, 'Please correct the error below.')
            return HttpResponse("<h1>Something went wrong<br/> Password couldnot be Updated<br/> Please try again</h1>")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'first/change_password.html', {'form': form})


def python(request, user_id=1):
    a=[]

    if request.method == "POST":
        patientid = request.POST.get('param')
        patient = User.objects.get(pk = patientid)
        document = Document()
        document.user = patient

        for document in patient.document_set.all():
            a.append(document.Document_image.url)

        #inp = request.POST.get('param')
        b = patient.Hospital_id
        out = run([sys.executable,'C:\\python\\Python38\\code10.py',str(a),str(b)], shell=False , stdout=PIPE )
        print(out)

        return render(request,'first/python.html',{'out':out.stdout})
    else:
        patient = get_object_or_404(User, pk=user_id)

        return render(request,'first/python.html',{'patient':patient})

first/templates/first/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Medical Record Documentation System{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'first/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand"  href="{% url 'first:home' %}"><span class="glyphicon glyphicon-home " aria-hidden="true"></span>  Medical Record Documentation System </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'first:index' %}"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Dashboard</a></li>

            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'first:search' %}">
                <div class="form-group">
                    <input type="search" class="form-control" placeholder="Enter Hospital ID" name="search" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_superuser %}
                        <li><a href="{% url 'first:hospital_user'%}"><span class="glyphicon glyphicon-user"></span> Admin. {{request.user.first_name}} {{request.user.last_name}}</a></li>
                    {% elif request.user.is_staff %}
                         <li><a href="{% url 'first:hospital_user'%}"><span class="glyphicon glyphicon-user"></span> Doctor. {{request.user.first_name}} {{request.user.last_name}}</a></li>
                    {% else %}
                         <li><a href="{% url 'first:hospital_user'%}"><span class="glyphicon glyphicon-user"></span> Staff. {{request.user.first_name}} {{request.user.last_name}}</a></li>
                    {% endif%}

                <li><a href="{% url 'first:logout_user'%}""><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                </ul>

            {% else %}
                <ul class="nav navbar-nav navbar-right">

                <li><a href="{% url 'first:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>


            {% endif %}

            {% if not request.user.is_staff or request.user.is_superuser %}

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'first:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Document
                    </a>
                </li>
            </ul>

            {% endif %}

            {% if request.user.is_staff %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'first:view' %}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp; View
                    </a>
                </li>
            </ul>
            {% endif %}

            {% if user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/admin" target="_blank" >
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Admin Site
                    </a>
                </li>
            </ul>
                    {% endif %}

            {% endif %}


        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

first/templates/first/change_password.html
{% extends 'first/base.html' %}
{% block title %} Change Password {% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <br/>
    <button type="submit" class="btn btn-success">Save Changes</button>

</form>

{% endblock %}

first/templates/first/create.html
{% extends 'first/base.html'  %}

{% block title %} Add a Document {% endblock %}

{% block body %}
Add New Document
<form method="post" action="{% url 'first:home' %}">
    {% csrf_token %}
    {{form}}
    <button type="submit", name="Add Record">Add Record </button>
</form>
{% endblock %}

first/templates/first/detail.html
{% extends 'first/base.html' %}
{% block title %} Patient Details {% endblock %}

{% block body %}

{% if user.is_authenticated %}
<h2>Name: {{patient.Firstname}}</h2>
<h2>Age: {{patient.Age}}</h2>
<h2>Hospital ID: {{patient.Hospital_id}}</h2>
<ol>
    {% if patient.document_set.all %}
        {% for document in patient.document_set.all %}
    <li> <h3><u>{{document.Document_type}}</u></h3> <br> <img src = "{{document.Document_image.url}}" height="1000" width="1000"/> </li>
        {% endfor %}

    {% else %}
    <h3>No Documents Found</h3>

    {% endif %}
</ol>

{% else %}
    <h2>Please Login to Access the records</h2>
{% endif %}



{% endblock %}

first/templates/first/document_form.html
{% extends 'first/base.html' %}
{% block title %}Add Documents{% endblock %}


{% block body %}

{% if user.is_authenticated %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a Document</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post"  enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'first/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add Record</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% else %}
     <h2>Please Login to Access the records</h2>
{% endif %}

{% endblock %}

first/templates/first/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="Hospital_id">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

first/templates/first/hospital_user.html
{% extends 'first/base.html' %}
{% block title %}Details{% endblock %}


{% block body %}

{% if user.is_authenticated %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Welcome {{request.user.first_name}} {{request.user.last_name}} </h3> <br/><br/>
                    <h3><u>Details</u></h3>    <br/>
                    <h4>First Name : {{request.user.first_name}} </h4> <br/>
                    <h4>Last Name : {{request.user.last_name}} </h4> <br/>
                    <h4>Email ID : {{request.user.email}} </h4> <br/>
                    {% if not request.user.is_staff %}
                        <h4> Designation : Staff </h4>


                    {% elif request.user.is_superuser %}
                        <h4> Designation : Admin </h4>


                    {% elif request.user.is_staff %}
                        <h4> Designation : Doctor </h4>

                    {% endif %}


                    <br/>
                    <a href="{% url 'first:change_password'%}">
                    <button type="submit" class="btn btn-success">Change Password</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

first/templates/first/index.html
{% extends 'first/base.html' %}


{% block body %}

{% if user.is_authenticated %}
    <div class="document-container container-fluid">

    <!-- Albums -->
    {% for patient in all_users %}
    <div class="row">
        <div class="col-sm-12">

            <h3> <strong> <u>{{patient.Hospital_id}} - {{patient.Firstname}}'s Document </u> </strong> </h3>
            {% if request.user.is_superuser or request.user.is_staff %}
                 <a href="{% url 'first:python' patient.id%}" class="btn btn-success" role="button">Generate Document</a> <br/>
            {% endif %}
        </div>
        {% if patient.document_set.all %}
            {% for document in patient.document_set.all %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'first:record' patient.id %}">
                            <img src="{{ Document.document_image }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ document.Document_type }}</h2>
                            <h4>{{ document.Hospital_id }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'first:record' patient.id document.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                               <form action="{% url 'first:delete_document' patient.id document.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="document_id" value="{{ document.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                               </form>



                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'first:create' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Document
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
    {% endfor %}

{% else %}
     <h2>Please Login to Access the records</h2>

{% endif %}


{% endblock %}

first/templates/first/login.html
{% extends 'first/base.html' %}
{% block title %}Log In{% endblock %}


{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'first:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

first/templates/first/python.html
{% extends 'first/base.html' %}

{% block title %} Python Code {% endblock %}

{% block body %}

<form action ="{% url 'first:python' %}" method = "post" >

    {% csrf_token %}
<!--
    {% for document in patient.document_set.all %}
         {{ document.Document_image.url }}
    {% endfor %}
-->
    Patient ID :
    <input type="text" name="param" required value=" {{patient.id}}">  <br/>

    {{data_external}} <br/><br/>
    {{out}}

    <input type="submit" class="btn btn-success" value="Generate Document">
</form>

{% endblock %}

first/templates/first/record.html
{% extends 'first/base.html' %}
{% block title %} Patient Details {% endblock %}

{% block body %}

{% if user.is_authenticated %}
<h3>Name: {{patient.Firstname}}</h3>
<h3>Age: {{patient.Age}}</h3>
<h3>Hospital ID: {{patient.Hospital_id}}</h3>
<h3><strong> Document Type: <u> {{document.Document_type}} </u> </strong></h3>
<br/>
<img src = "{{document.Document_image.url}}" height="1000" width="1000"/>

{% else %}
    <h2>Please Login to Access the records</h2>
{% endif %}

{% endblock %}

first/templates/first/search.html
{% extends 'first/base.html' %}

{% block body %}

{% if user.is_authenticated %}

{% if patients %}
{% for patient in patients %}

<div class="row">
        <div class="col-sm-12">

            <h3> <strong> <u>{{patient.Hospital_id}} - {{patient.Firstname}}'s Document </u> </strong> </h3>
            {% if request.user.is_superuser or request.user.is_staff %}
                 <a href="{% url 'first:python' patient.id%}" class="btn btn-success" role="button">Generate Document</a> <br/>
            {% endif %}
        </div>
        {% if patient.document_set.all %}
            {% for document in patient.document_set.all %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'first:record' patient.id %}">
                            <img src="{{ Document.document_image }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ document.Document_type }}</h2>
                            <h4>{{ document.Hospital_id }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'first:record' patient.id document.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <form action="{% url 'first:delete_document' patient.id document.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="document_id" value="{{ document.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
</div>


{% endfor %}

{% else %}
    <h3>No Patient Found. <br/> <br/>Kindly verify the Hospital ID of the Patient </h3>

{% endif %}

{% else %}
     <h2>Please Login to Access the records</h2>

{% endif %}


{% endblock %}

first/templates/first/view.html
{% extends 'first/base.html' %}
{% block title %} Patient Lists {% endblock %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>




{% if user.is_authenticated %}

     {% if all_users %}



    <ol>
        <h2> List of Patients </h2>
        {% for user in all_users %}

        <li> <a href="/first/{{user.id}}/"> <h3> {{user.Firstname}} - {{user.Hospital_id}}  </h3> </a> </li>
        {% endfor %}
    </ol>

    {% else %}
        <h3> No Users Found </h3>
     {% endif %}
{% else %}
     <h2>Please Login to Access the records</h2>
{% endif %}

</body>
</html>

{% endblock %}